name: Deploy To  CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH And Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: 22
        # git fetch后再reset的操作是为了强制拉取（不考虑本地冲突直接覆盖）
        script: |
          ls
          cd /project/github_action_demo
          git fetch --all
          git reset --hard origin/master
          yarn
          yarn build
